### ISSUE TITLE
Prompt outputs failed validation after updating to v0.9.6.4 (2025-07-12 11:05:29)

### ISSUE THREAD

**Issue by rmcc3** [mcmonkeyprojects/SwarmUI#890]
### Expected Behavior

Generate the prompt

### Actual Behavior

```
All available backends failed to load the model 'E:/SwarmUI/Models/diffusion_models/WAN/wan2114BFusionx_fusionxT2VGgufQ3KS.gguf'.

Possible reason: ComfyUI errored: {
  "error": {
    "type": "prompt_outputs_failed_validation",
    "message": "Prompt outputs failed validation",
    "details": "Exception when validating node: validate_inputs() missing 1 required positional argument: 'validated'",
    "extra_info": {}
  },
  "node_errors": {
    "102": {
      "errors": [
        {
          "type": "exception_during_validation",
          "message": "Exception when validating node",
          "details": "validate_inputs() missing 1 required positional argument: 'validated'",
          "extra_info": {
            "exception_type": "TypeError",
            "traceback": [
              "  File \"E:\\SwarmUI\\dlbackend\\comfy\\ComfyUI\\execution.py\", line 850, in validate_prompt\n    m = validate_inputs(prompt, o, validated)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"
            ]
          }
        }
      ],
      "dependent_outputs": [
        "102"
      ],
      "class_type": "SwarmJustLoadTheModelPlease"
    }
  }
}
```

### Steps to Reproduce

Load a WAN model (all trigger the error), and attempt to generate a prompt.

### Debug Logs

```
2025-07-12 19:44:02.614 [Error] [BackendHandler] Backend request #4 failed: All available backends failed to load the model 'E:/SwarmUI/Models/diffusion_models/WAN/wan2114BFusionx_fusionxT2VGgufQ3KS.gguf'.

Possible reason: ComfyUI errored: {
  "error": {
    "type": "prompt_outputs_failed_validation",
    "message": "Prompt outputs failed validation",
    "details": "Exception when validating node: validate_inputs() missing 1 required positional argument: 'validated'",
    "extra_info": {}
  },
  "node_errors": {
    "102": {
      "errors": [
        {
          "type": "exception_during_validation",
          "message": "Exception when validating node",
          "details": "validate_inputs() missing 1 required positional argument: 'validated'",
          "extra_info": {
            "exception_type": "TypeError",
            "traceback": [
              "  File \"E:\\SwarmUI\\dlbackend\\comfy\\ComfyUI\\execution.py\", line 850, in validate_prompt\n    m = validate_inputs(prompt, o, validated)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"
            ]
          }
        }
      ],
      "dependent_outputs": [
        "102"
      ],
      "class_type": "SwarmJustLoadTheModelPlease"
    }
  }
}
2025-07-12 19:44:02.615 [Debug] [BackendHandler] Backend request #4 finished.
2025-07-12 19:44:02.615 [Debug] Refused to generate image for local: All available backends failed to load the model 'E:/SwarmUI/Models/diffusion_models/WAN/wan2114BFusionx_fusionxT2VGgufQ3KS.gguf'.

Possible reason: ComfyUI errored: {
  "error": {
    "type": "prompt_outputs_failed_validation",
    "message": "Prompt outputs failed validation",
    "details": "Exception when validating node: validate_inputs() missing 1 required positional argument: 'validated'",
    "extra_info": {}
  },
  "node_errors": {
    "102": {
      "errors": [
        {
          "type": "exception_during_validation",
          "message": "Exception when validating node",
          "details": "validate_inputs() missing 1 required positional argument: 'validated'",
          "extra_info": {
            "exception_type": "TypeError",
            "traceback": [
              "  File \"E:\\SwarmUI\\dlbackend\\comfy\\ComfyUI\\execution.py\", line 850, in validate_prompt\n    m = validate_inputs(prompt, o, validated)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"
            ]
          }
        }
      ],
      "dependent_outputs": [
        "102"
      ],
      "class_type": "SwarmJustLoadTheModelPlease"
    }
  }
}
```

### Other

This issue is occurring after I updated to the latest commit 0d43595d4cdf653c453799ca38c8bad78a2b36c7. I did not have this issue prior.

**Comment by krahnikblis** [comment]
Very bad advice deleted

**Comment by AshtakaOOf** [comment]
Please update your ComfyUI backend.

**Comment by mcmonkey4eva** [comment]
Comfy made a breaking change that led to incompatibility with things, you need to make sure both SwarmUI and the Comfy backend are fully updated to latest.

For Swarm, just hit server -> update & restart button

For comfy backend, server -> backends -> AutoUpdate, make sure it's enabled. If it already was enabled, swap it to Forced.

**Comment by C47HERINE** [comment]
> Very bad advice deleted

Thanks for that! Nothing seemed to work, neither updating or reinstalling.. But [the wrong way appeared to] worked.

**Comment by mcmonkey4eva** [comment]
Absolutely do not do that no

**Comment by C47HERINE** [comment]
> Absolutely do not do that no

I know… for now I’m using a standalone ComfyUI install, but honestly it’s so much work just to get the initial setup right. I’m planning to do a clean install of Swarm later and see if that sorts it out.

By the way, thanks so much for your exceptional work! You got me to move on from Fooocus last year, I started with SDXL, then Flux, then LLMs, and now video generation. All because of Swarm. ComfyUI is great, but it can be such a hassle… after an hour and 24 nodes, I finally get the same results I’d have with Swarm in 2 minutes.

Keep up the amazing work, it really makes a huge difference!

**Comment by naccan55** [comment]
I had this same issue after not using Swarm for the weekend and updating and restarting SwarmUI fixed it for me. Thank you for the helpful advice.
